[package]
name = "bsmetadl"
version = "0.1.0"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
diesel = { version = "1.4.5", features = ["sqlite"] }
dotenv = "0.15.0"
reqwest = { version = "0.10", features = ["blocking", "brotli", "gzip"] }
#rusqlite = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
zip = "0.5"
